# Numpy

In [ ]:
listt = [1,2,3,4,5]

In [ ]:
# pip install numpy

In [2]:
import numpy as np 

In [7]:
# Python list
py_list = [1, 2, 3, 4, 5]

print(type(py_list))

print(py_list)

<class 'list'>
[1, 2, 3, 4, 5]


In [8]:
np_array = np.array(py_list)
print(np_array)

[1 2 3 4 5]


In [6]:
print(type(np_array))

<class 'numpy.ndarray'>


In [11]:
print(np.zeros(5))            # five zeros
print(np.ones(4))             # four ones

[0. 0. 0. 0. 0.]
[1. 1. 1. 1.]


In [20]:
print(np.arange(0, 10, 2))   # 0 to 9, step 2 (included, excluded)
print(np.linspace(0, 1, 5))  # 5 evenly spaced values from 0 to 1

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [ ]:
print(np.random.randint(1,100,5)) # starting 1, ending 100, total 5 valures

[59 37 83 33 65]


In [ ]:
# ludo -- dice 1,2,3,4,5,6
print(np.random.randint(1,7,1)) 

[5]


In [ ]:
# 10 
print(np.full(4, 10))                  # array of four 10

[10 10 10 10]


In [81]:
# data -- rows - 3 and columns 4
data = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

# print(data)
print(data.shape)    # (rows, columns)
print(data.dtype)    # data type of elements
print(data.ndim)     # number of dimensions
print(data.size)     # total number of elements

(3, 4)
int64
2
12


In [82]:
a = np.array([1, 2, 3])
b = np.array([1.0, 2.0, 3.0])
c = np.array([1, 2, 3], dtype=np.float32)

print(a.dtype)
print(b.dtype)
print(c.dtype)

int64
float64
float32


In [83]:
print(c)

[1. 2. 3.]


# Indexing and Slicing

In [ ]:
temps = np.array([22, 25, 19, 30, 28, 24, 21])

print(temps[0])        # first element
print(temps[-1])       # last elemen

22
21


In [89]:
print(temps[2:5])      # elements at index 2, 3, 4
print(temps[::2])      # every other element

print(temps[::3])      # every other element

[19 30 28]
[22 19 28 21]
[22 30 21]


In [ ]:
# 22, 30, 21 
# 22,
# 25,
# 19, 
# 30, - 3rd step
# 28,
# 24, 
# 21 - 3rd step

In [ ]:
grid = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12]
])

# shape rows 3 -- columns 4

In [97]:
print(grid[0:2, 1:3])  # subgrid — rows 0-1, cols 1-2

[[2 3]
 [6 7]]


In [107]:
print(grid[1:3, 1:3])
# 6 ,7
# 10, 11

[[ 6  7]
 [10 11]]


In [109]:
# 3,4
# 7,8
print(grid[0:2, 2:])

[[3 4]
 [7 8]]


In [ ]:
print(grid[0, 0])      # row 0, col 0  → 1
print(grid[1, 2])      # row 1, col 2  → 7
print(grid[2, -1])     # row 2, last col → 12
print(grid[0, :])      # entire first row
print(grid[:, 1])      # entire second column


1
7
12
[1 2 3 4]
[ 2  6 10]


In [117]:
a = np.array([1, 2, 3, 4, 5])
b = a[1:4].copy()
b[0] = 99
print(b)
print(a)

[99  3  4]
[1 2 3 4 5]


### 6.5 Array Operations

In [118]:
prices = np.array([100.0, 250.0, 75.0, 430.0, 90.0])

print(prices * 1.17)       # apply 17% tax to every price
print(prices - 10)         # discount of 10 from every price
print(prices / 100)        # convert to hundreds

[117.   292.5   87.75 503.1  105.3 ]
[ 90. 240.  65. 420.  80.]
[1.   2.5  0.75 4.3  0.9 ]


In [121]:
revenue = np.array([5000, 8000, 6500, 9200])
costs   = np.array([3200, 4100, 3900, 5500])

profit = revenue - costs
margin = (profit / revenue) * 100

print(profit)
print(np.round(margin, 1))

[1800 3900 2600 3700]
[36.  48.8 40.  40.2]


In [123]:
scores = np.array([88, 92, 74, 95, 61])
curved = scores + 5 # [5,5,5,5,5]
print(curved)

[ 93  97  79 100  66]


In [ ]:

print(np.sum(data))
print(np.mean(data))
print(np.median(data))
print(np.min(data))
print(np.max(data))
print(np.std(data))
print(np.var(data))

536
53.6
51.5
19
90
23.1179583873663
534.4399999999999


In [129]:
print(np.sort(data))

data = np.array([42, 67, 19, 85, 33, 71, 55, 48, 90, 26])
print(np.argmax(data))        # index of largest value
print(np.cumsum(data[:4]))    # running total of first 4 values

[19 26 33 42 48 55 67 71 85 90]
8
[ 42 109 128 213]


In [133]:
flat = np.arange(1, 13)       # [1, 2, 3, ... 12]
print(flat)
print(flat.shape)

matrix = flat.reshape(3, 4)   # 3 rows, 4 columns
print(matrix)
print(matrix.shape)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
